# .github/workflows/python-tests.yml
name: Python Tests & Local Coverage Badge

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests and coverage
      run: |
        PYTHONPATH=. coverage run -m pytest tests/
        coverage report -m --include="cnvpytor/fasta.py"
        coverage xml